name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run CPU/WASM benchmarks
      run: npm run benchmark:node
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results-${{ matrix.node-version }}
        path: benchmarks/
    
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      continue-on-error: true
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          const benchmarksDir = 'benchmarks';
          if (!fs.existsSync(benchmarksDir)) {
            console.log('No benchmark results found');
            return;
          }
          
          const results = fs.readdirSync(benchmarksDir)
            .filter(f => f.endsWith('.md'))
            .sort()
            .pop();
          
          if (results) {
            const content = fs.readFileSync(path.join(benchmarksDir, results), 'utf8');
            
            // Try to comment on PR
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## Benchmark Results\n\n${content}`
              });
              console.log('Successfully posted benchmark results to PR');
            } catch (error) {
              console.log('Could not post benchmark results to PR:', error.message);
              console.log('This is usually due to permission restrictions on forks');
              console.log('\n--- Benchmark Results ---\n');
              console.log(content);
            }
          }

  benchmark-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            install-cmd: npm ci
          - os: macos-latest
            install-cmd: npm ci
          - os: windows-latest
            install-cmd: npm ci --build-from-source
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install tfjs-node
      run: npm install @tensorflow/tfjs-node
      continue-on-error: true
    
    - name: Build
      run: npm run build
    
    - name: Run benchmarks with native backend
      run: npm run benchmark:native
      continue-on-error: true
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-native-${{ matrix.os }}
        path: benchmarks/